apiVersion: batch/v1
kind: Job
metadata:
  name: imager
spec:
  template:
    spec:
      containers:
        - image: imager
          name: imager
          resources:
            limits:
              cpu: "0.2"
              memory: "100Mi"
            requests:
              cpu: "0.1"
              memory: "50Mi"
          command: [ "sh", "-c" ]
          args: [ "/imager --input $(REPOSITORY_URL)" ]
          env:
            - name: REPOSITORY_URL
              value: "https://gist.githubusercontent.com/jmelis/c60e61a893248244dc4fa12b946585c4/raw/25d39f67f2405330a6314cad64fac423a171162c/sources.txt"
      restartPolicy: Never
