apiVersion: batch/v1
kind: Job
metadata:
  name: imager
spec:
  template:
    spec:
      containers:
        - image: imager
          name: imager
          resources:
            limits:
              cpu: "0.2"
              memory: "100Mi"
            requests:
              cpu: "0.1"
              memory: "50Mi"
          args: [ "--input", "${REPOSITORY_URL}" ]
          env:
            - REPOSITORY_URL:
      restartPolicy: Never
